language: julia

os:
  - linux
  - osx

codecov:  true
coveralls: true

julia:
  - 1.3
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

after_success:
  # Submit test coverage report
  #- julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # Build and deploy documentation
  - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
  - julia --project=docs/ docs/make.jl
