language: julia

os:
  - linux
  - osx

codecov: true
coveralls: true

julia:
  - 1.3
  - nightly

notifications:
  email: false

jobs:
  allow_failures:
    - env: TRAVIS_JULIA_VERSION=nightly
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
