language: julia

codecov: true
coveralls: true

notifications:
  email: false

jobs:
  allow_failures:
    - env: TRAVIS_JULIA_VERSION=nightly
  include:
    ### Tests
    - stage: "Test (Julia 1.3)"
      julia: 1.3
      os: linux
      script:
        -  julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'
    - stage: "Test (Julia nightly)"
      julia: nightly
      os: linux
      script:
        -  julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'
    ### Documentation generation
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
