language: julia

notifications:
  email: false

jobs:
  allow_failures:
    - env: TRAVIS_JULIA_VERSION=nightly
    - os: osx
    - os: windows
  include:
    ###### Tests
    ### Julia 1.3
    - stage: "Unit tests"
      name: "Unit tests (Julia 1.3) (Linux)"
      julia: 1.3
      os: linux
      script:
        -  julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test(coverage=true)'
      after_success:
        # Code coverage
        - julia -e 'using Pkg; Pkg.add("Coverage");'
        - julia -e 'using Coverage; Coveralls.submit(Coveralls.process_folder());'
        - julia -e 'using Coverage; Codecov.submit(Codecov.process_folder());'

    - stage: # Unit tests
      name: "Unit tests (Julia 1.3) (OSX)"
      julia: 1.3
      os: osx
      script:
        -  julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'

    - stage: # Unit tests
      name: "Unit tests (Julia 1.3) (Windows)"
      julia: 1.3
      os: windows
      script:
        -  julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'

    ### Julia nightly
    - stage: # Unit tests
      name: "Unit tests (Julia nightly) (Linux)"
      julia: nightly
      os: linux
      script:
        -  julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'

    - stage: # Unit tests
      name: "Unit tests (Julia nightly) (OSX)"
      julia: nightly
      os: osx
      script:
        - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'
      julia: nightly

    - stage: # Unit tests
      name: "Unit tests (Julia nightly) (Windows)"
      os: windows
      script:
        - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'

    ### Documentation generation
    - stage: "Documentation"
      julia: 1.3
      python: 3.7
      os: linux
      script:
        - pip install --user matplotlib
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
