language: julia

os: linux
dist: bionic

notifications:
  email: false

jobs:

  allow_failures:
    - julia: 1.4
    - julia: nightly

  include:

    ########################################################
    ### Unit testing
    ########################################################

    - stage: "Unit testing"
      julia: 1.3
      after_success:
        # Code coverage
        - julia -e 'using Pkg; Pkg.add("Coverage");'
        - julia -e 'using Coverage; Coveralls.submit(Coveralls.process_folder());'
        - julia -e 'using Coverage; Codecov.submit(Codecov.process_folder());'

    - stage: 
      julia: 1.4

    - stage:
      julia: nightly

    ########################################################
    ### Documentation generation
    ########################################################

    - stage: "Documentation"
      julia: 1.3
      install:
        - sudo apt-get update
        - sudo apt-get install -y python3.7 python3-pip python3-setuptools
        - pip3 install --upgrade pip
        - pip3 install --user matplotlib
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()));'
        - julia --project=docs -e 'using Pkg; Pkg.build("PyCall");'
      script:
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip

script:
  - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test(coverage=true)'
